import type {
  ConnectionConfig,
  GenerationParameters,
  PersistedPreferences,
  ServerCapabilities,
  WorkspaceSession,
} from '../domain/types'
import { randomHex, randomUuid } from './ids'

export const DEFAULT_CONNECTION: ConnectionConfig = {
  transport: 'bridge',
  protocol: 'http',
  host: '127.0.0.1',
  port: 7859,
  tls: false,
  apiBasePath: '',
  sharedSecret: '',
  rememberSecret: false,
  clientName: 'Draw Things Local Canvas',
  bridgeUrl: 'http://127.0.0.1:47821',
  bridgePairingToken: '',
  allowSelfSignedCertificate: true,
  tlsFingerprintSha256: '',
  expectedBridgeMode: false,
  expectedResponseCompression: true,
  expectedModelBrowsing: false,
}

export const DEFAULT_PARAMETERS: GenerationParameters = {
  model: '',
  width: 1024,
  height: 1024,
  seed: -1,
  guidance_scale: 5,
  seed_mode: 'Scale Alike',
  steps: 16,
  batch_count: 1,
  batch_size: 1,
  sampler: 'DPM++ 2M AYS',
  strength: 1,
  clip_skip: 2,
  image_guidance: 1.5,
  mask_blur: 2.5,
  mask_blur_outset: 0,
  sharpness: 0,
  clip_weight: 1,
  negative_prompt_for_image_prior: true,
  image_prior_steps: 5,
  hires_fix: false,
  hires_fix_width: 1024,
  hires_fix_height: 1024,
  hires_fix_strength: 0.7,
  tiled_decoding: false,
  decoding_tile_width: 640,
  decoding_tile_height: 640,
  decoding_tile_overlap: 128,
  original_width: 1024,
  original_height: 1024,
  crop_top: 0,
  crop_left: 0,
  target_width: 1024,
  target_height: 1024,
  negative_original_width: 512,
  negative_original_height: 512,
  aesthetic_score: 6,
  negative_aesthetic_score: 2.5,
  zero_negative_prompt: true,
  refiner_model: '',
  refiner_start: 0.7,
  num_frames: 14,
  fps: 5,
  motion_scale: 127,
  guiding_frame_noise: 0.02,
  start_frame_guidance: 1,
  shift: 1,
  stage_2_guidance: 1,
  stage_2_shift: 1,
  loras: [],
  controls: [],
  stochastic_sampling_gamma: 0.3,
  preserve_original_after_inpaint: true,
  tiled_diffusion: false,
  diffusion_tile_width: 1024,
  diffusion_tile_height: 1024,
  diffusion_tile_overlap: 128,
  upscaler: '',
  upscaler_scale: 0,
  t5_text_encoder_decoding: true,
  separate_clip_l: false,
  clip_l_text: '',
  separate_open_clip_g: false,
  open_clip_g_text: '',
  speed_up_with_guidance_embed: true,
  guidance_embed: 3.5,
  resolution_dependent_shift: true,
  tea_cache_start: 5,
  tea_cache_end: -1,
  tea_cache_threshold: 0.06,
  tea_cache_max_skip_steps: 3,
  tea_cache: false,
  separate_t5: false,
  t5_text: '',
  causal_inference: 0,
  causal_inference_pad: 0,
  cfg_zero_star: false,
  cfg_zero_init_steps: 0,
  compression_artifacts: 'disabled',
  compression_artifacts_quality: 43.1,
  color_calibration: 'none',
  expand_prompt_to_json: false,
  restore_faces: false,
}

export const EMPTY_CAPABILITIES: ServerCapabilities = {
  protocol: 'http',
  canGenerate: false,
  canImageToImage: false,
  canStreamProgress: false,
  canCancel: false,
  canBrowseModels: false,
  requiresHttpModeForCanvas: false,
  sharedSecretRequired: false,
  models: [],
  loras: [],
  controls: [],
  textualInversions: [],
  limitations: [],
}

export const DEFAULT_PREFERENCES: PersistedPreferences = {
  version: 1,
  connectionConfigured: false,
  connection: DEFAULT_CONNECTION,
  parameters: DEFAULT_PARAMETERS,
  negativePrompt: '',
  advancedPanelOpen: false,
  compactSidebar: false,
}

export function createPairingToken() {
  return randomHex(32)
}

export function createSession(title = '새 캔버스'): WorkspaceSession {
  const now = Date.now()
  return {
    id: randomUuid(),
    title,
    createdAt: now,
    updatedAt: now,
    turns: [],
    items: [],
    view: { x: 0, y: 0, zoom: 1 },
    continuationEnabled: true,
    draftPrompt: '',
    useSelectedImage: false,
  }
}
